development:
  adapter: postgresql
  encoding: unicode
  database: kopool_development
  pool: 5
  username: kopool
  password: sixstair

test:
  adapter: postgresql
  encoding: unicode
  database: kopool_test
  pool: 5
  username: kopool
  password: sixstair

production:
  adapter: postgresql
  encoding: unicode
  database: kopool_production
  pool: 5
