default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['postgres_username'] %>
  password: <%= ENV['postgres_password'] %>

development:
  database: kopool_development

test:
  database: kopool_test

production:
  adapter: postgresql

